language: go

matrix:
  include:
    - go: 1.13.x
      env: STABLE=true
    - go: 1.12.x

cache:
  directories:
    - $GOPATH/pkg/mod

env:
  global:
    - GO111MODULE=on

install:
  - go mod tidy
  - git diff --exit-code go.mod
  - git diff --exit-code go.sum
  - go mod download

script:
  - go test -v -cover ./...
